---
title: "《R语言基础》教学大纲"
author: |
    | 大数据分析基础系列
#date: "`r format(Sys.time(), '%B %d, %Y')`"
documentclass: ctexart
fontsize: 12pt
geometry: tmargin=1.8cm, bmargin=1.8cm, lmargin=2.1cm, rmargin=2.1cm
output:
#  pdf_document:  
  rticles::ctex:
    keep_tex: true
    fig_caption: yes
    number_sections: yes
    toc: yes
    latex_engine: xelatex
classoption: "hyperref,"
header-includes: 
  - \usepackage{fontspec, xunicode, xltxtra}    
  - \usepackage{xeCJK,ctex}
  - \usepackage{bm,xcolor}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[LE,LO]{《R语言基础》}
  - \fancyhead[RE,RO]{《大数据分析基础》系列}
#  - \fancyhead[RE,RO]{}  
#  - \fancyhead[LE,LO]{}
  - \fancyfoot[RE,RO]{\thepage}
  - \fancyfoot[CO,CE]{上海数萃大数据学院}  
# 设置页眉线与页脚线宽度与颜色
  - \renewcommand{\headrule}{{\color{red}\hrule width\headwidth height\headrulewidth \vskip-\headrulewidth}}
  - \renewcommand{\footrule}{{\color{black}\vskip-\footruleskip\vskip-\footrulewidth \hrule width\headwidth height\footrulewidth\vskip\footruleskip}}
  - \renewcommand{\headrulewidth}{0.8pt}
  - \renewcommand{\footrulewidth}{0.6pt}
  - \renewcommand\contentsname{\bfseries 大纲目录}  
# 定制章节标题格式 
  - \usepackage[sf,raggedright]{titlesec}
  - \usepackage{titletoc}
  - \titleformat{\section}{\bfseries\large\color{blue}}{\bfseries\thesection}{0.5em}{}
#  - \titleformat{\subsection}{\bfseries\large}{\bfseries\thesubsection}{0.5em}{}
  - \titlespacing{\section}{0pt}{3.5ex plus .1ex minus .2ex}{1.5\wordsep}
#  - \titlespacing{\subsection}{0pt}{1.5ex plus .1ex minus .2ex}{\wordsep}
# hyperline
  - \hypersetup{colorlinks=true, breaklinks=true, linkcolor=blue}
---


\newpage

\noindent\textbf{课程名称}: R语言基础

\noindent\textbf{适合专业}: 数据科学与大数据技术、大数据技术与应用、统计学、应用统计学、统计统计、应用数学等本科专业

# 课程目的、任务

本课程是为数据科学与大数据技术及相关专业学生开设的一门课程，《R语言基础》是一门基于R进行数据分析的基础课程，本课程的目的是帮助学生从零开始对R语言有全方位了解，掌握R语言数据处理、统计分析和可视化最为基础知识、技术和基本应用，为使用R语言进行深入的数据分析与行业应用打下扎实的基础。本课程是后期统计分析、机器学习、可视化等相关课程的预修课程。

# 课程简介

-	R语言是一个自由、免费、源代码开放的语言环境。它功能完备，语言灵活且不依赖操作系统，是一个用于统计计算和统计制图的优秀工具。在2010 年，美国统计协会（ ASA）授予R 语言为(第⼀届)统计计算及图形奖。截止目前为止，R是数据科学领域使用用户最多的数据挖掘与编程语言，且其用户数量在不断增加。R已经成为几乎所有国内外高校统计类课程标配的教学软件，R的书集遍及经济、金融、生物、医学、生态、电子商务、航空、旅游、心理、法律等各个领域，并成大数据分析的宠儿: 覆盖机器学习、人工智能和可视化等。R语言在国内业界也逐步成为主流的分析工具，每年全国性的R语言会议推进R的迅猛发展。

-	本课程共5大模块，从R入门、R数据集创建与管理、R绘图初步、R数据探索与比较分析和R统计建模等方面，让零基础学员从各个角度对R的使用进行学习。

-	本课程为基础课程，学员可以通过学习对R语言进行全方位的了解与掌握，并为R的进阶学习与实际数据分析做好基础铺垫。


# 教学方式和实践环节的特色

- 教学方式：课堂讲授，配合大数据平台演示。

- 实践环节：

    1. 课堂讲授中提供一定的思考题供学生练习或讨论；
    
    2. 课后布置作业，作业量2---3小时，作业中以基本练习为主。

# 教材及参考书目

- 建议教材: 

    1. R.I. Kabacoff著, 高涛,肖南, 陈钢译, R语言实战(R in Action: Data Analysis and Graphics with R), 人民邮电出版社, 2013.

    1. 徐珉久[韩], 武传海 (译). R语言与数据分析实战. 中国工信出版集团，人民邮电出版社, 2017.1

- 参考书目:

    1. 汤银才, R语言与统计分析, 高等教育出版社. 2008

    1. Joseph Adler, R in a Nutshell, California: O’Reilly Meda, Inc., 2nd Ed. 2012. 

    1. Jared P. Lander, R for Everyone: Advanced Analytics and Graphics. New York: Addison-Wesley. 2014.

    1. Hadley Wickham, Garrett Grolemund, R for Data Science - Import，Tidy，Transform，Visualize, and Model data, O'Reilly. 2017. 

    1. Jim Albert, M. Rizzo, R by example, Springer, 2012. 

    1. Prabhanjan N. Tattar, Suresh Ramaiah, B.G. Manjunath. A Course in Statistics with R(ACSWR), for master students. Wiley. 2016. [*] 

    1. Norman Matloff.  The art of R programming, No Starch Press, inc., 2011.

    1. Paul Murrell, R Graphics, Chapman & Hall/CRC. 2006.

    1. Deepayan Sarkar, Lattice: Multivariate Data Visualization with R, Springer. 2008.

    1. Hadley Wickham, ggplot2: Elegant Graphics for Data Analysis, Springer. 2009. (中译本: 殷腾飞,统计之都, 2014)

    1. Donato Teutonico, ggplot2 Essentials, PACKT, 2015. 

    1. Alboukadel Kassambara, ggplot2 - Guide to Create Beautiful Graphics in R (2nd Ed). 2013. 

    1. Mark P.J. van der Loo, Edwin de Jonge, Learning Rstudio for R Statistical Computing. PACKT,  2012. 

    1. John Verzani, Getting Started with Rstudio, OReilly, 2011. 

    1. Nicholas J. Horton and Ken Kleinman. Using R and RStudio for Data Management Statistical Analysis and Graphics(2nd Ed.)，2015.


# 考核方式与评价结构比例

- 考核内容为：平时表现、作业完成情况、平时测验、期终闭卷考试。

- 评价结构比例：

    1. 总评成绩由平时成绩和考试成绩两部分组成，一般平时成绩占40%，考试成绩占60%。

    2．平时成绩由平时表现、作业、平时测验成绩组成，一般平时表现占10%，作业占30%，平时测验成绩占60%。

# 讲授大纲

**M1：R入门**

1. 大数据与数据科学

  	- 数据科学与分析工具
  	- R及其优势
  	- R安装与配置
  	- R包安装与使用
  	- R资源与帮助

2. R快速入门教程

    - R中的基本语法
    - R中的数据对象及其属性
    - R的工作空间与管理
    - R编程基础
    - R程序调试

3. R编辑器与RStudio

  	- R常用编辑器
  	- Rstudio功能与使用技巧
  	- Rstudio进阶
  	- 项目管理	

4. Rmarkdown介绍

    - Rmarkdown
    - 文学化统计编程


**M2：R数据集创建与管理**

1. 数据集的创建与处理

    - 常用数据对象与创建

    - 数据的读取

    - 数据的存储

    - 数据集的处理

    - 数据集的合并与子集提取

    - 缺失值的处理

    - 数据表数据的切片、切块与组合


2. 向量的操作

    - 合并数据框的行(向量)与列(向量)
  	
  	- apply系列函数 
  	
  	- 数据分组并调用函数
  	
  	- 数据拆分与合并
  	
  	- 数据排序
  	
  	- 访问数据中的列
  	
  	- 查找符合条件的数据索引
  	
  	- 分组运算

3. 数据对象的其他操作

    - 赋值与常用运算
  	
  	- 基本的数学运算
  	
  	- 用于矩阵的运算
  	
  	- 正则表达式
  	
  	- 与统计分布相关的函数


**M3：R绘图初步**

1. 基本的绘图命令

    - 大趋势：信息可视化
  	- R绘图基础: 低级与高级绘图命令
  	- 基本绘图函数: plot, points, lines, curve，par
  	- 绘图三要素设置详解(颜色，点型，线型)
  	- 绘图信息补充(title,text,legend,axis)
  	- R窗口和图形设备（X11，pdf，png）

2. 一维数据的可视化

  	- 常用统计分布与4类函数
  	- 一维离散变量的分布图示
    - 一维连续变量的分布图示
  	- 一维连续分布诊断图
  	- 非参数密度估计与展示

3. 多维数据的可视化

  	- 二个离散变量的分布图示
  	- 二个混合变量的分布图示
  	- 二个连续变量的分布图示
    - 多变量的可视化

**M4：R统计分析初步**

1. 数据分析基础

2. R中常用的统计函数

3. 描述性统计分析
    
    - 常用描述性统计量及其计
    - 单个连续型变量描述性统计量的获取
    - 分组计算描述性统计量

4. 相关性分析

5. 相关性检验

**M5：R统计建模**

1. 回归模型

    - lm()函数中的公式表示
    - 一元线性回归
    - 多元线性回归
    - 回归预测

2. 分类数据的统计推断
    
    - 广义线性模型概述
    - glm()函数介绍
    - Logistic回归
    - Poisson回归

3. 模型的检验与比较
    
    - 回归模型诊断
    - 变量的选择
    - 模型比较
    - 异常值判断
    - 预测与交叉验证 


